---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-acl
rules:
  - apiGroups: [""]
    resources:
      - "secrets"
    verbs:
      - "get"
      - "watch"
      - "list"
