# four node (3 workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: caldera
networking:
  ipFamily: ipv4
  disableDefaultCNI: true
  podSubnet: "10.10.0.0/16"
  serviceSubnet: "10.11.0.0/16"
nodes:
  - role: control-plane
    image: kindest/node:v1.25.3
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        name: "control-plane"

  - role: worker
    image: kindest/node:v1.25.3
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        name: "worker-01"

  - role: worker
    image: kindest/node:v1.25.3
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        name: "worker-02"

  - role: worker
    image: kindest/node:v1.25.3
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        name: "worker-03"
