---
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: argocd-vault-plugin-kustomize
spec:
  generate:
    command:
      - "/bin/bash"
      - "-c"
    args:
      - "kustomize build . | argocd-vault-plugin generate -"
